### ISSUE TITLE
Bot throwing up error - see below

### ISSUE THREAD

**Issue by WallyNZ** [JeanOUINA/VitaBot#2]
$VITC tipbot 🍑
BOT
 — Today at 8:12 AM
The command ticketstatus threw an error! Sorry for the inconvenience! Please report this to VitaBot's github:
Go to VitaBot's github
DiscordAPIError: Your bot has been flagged by our anti-spam system for abusive behavior. Please reach out to our team by going to https://dis.gd/report and appeal this action taken on your bot.

Vitamin.Tips

**Comment by JeanOUINA** [comment]
Hi, this should be fixed if you dm the bot at least once from now.
