### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by sebrock** [JeanOUINA/VitaBot#3]
![image](https://user-images.githubusercontent.com/156824/151662573-3ea1143b-f0b7-4b1a-a689-318564b21779.png)

**Comment by JeanOUINA** [comment]
Vite is having issue, I can try something, hold on

**Comment by JeanOUINA** [comment]
Fixed.

**Comment by sebrock** [comment]
Thanks @JeanOUINA 
Was your solution to use your own node?
Anyways the network itself is kinda borked at this point.-

**Comment by JeanOUINA** [comment]
> Was your solution to use your own node?
Yup. I usually use my own node, but for some reason it wasn't working on monday and i didn't have that much time to debug. I switched it on vite's official node and forgot to put it back.
> Anyways the network itself is kinda borked at this point.-
Yeah, but you can also use my node which is overall faster, has better PoW and is overall more stable than vite's node 
https://node-vite.thomiz.dev/
