### ISSUE TITLE
Error code -32002

### ISSUE THREAD

**Issue by sebrock** [JeanOUINA/VitaBot#4]
`Error: {"jsonrpc":"2.0","id":54619411,"error":{"code":-32002,"message":"invalid character 'T' looking for beginning of value"}}`

![image](https://user-images.githubusercontent.com/156824/155612129-61f2417e-0391-4946-a999-4e265ad71750.png)

**Comment by JeanOUINA** [comment]
PoW Server is down, we’re looking into it.

**Comment by sebrock** [comment]
Working as expected at this time, closing issue.
